package com.xiaomi.infra.pegasus.spark.bulkloader;

import com.xiaomi.infra.pegasus.spark.Config;
import com.xiaomi.infra.pegasus.spark.PegasusSparkException;

public class BulkLoaderConfig extends Config {

  public String dataPathRoot = "/pegasus-bulkloader";
  // todo(jiashuo): tableId, tablePartitionCount should be automatically get by clusterName and
  // tableName
  public int tableId;
  public int tablePartitionCount;
  public boolean isDistinct = false;
  public boolean isSort = true;

  public BulkLoaderConfig(
      String remoteFsUrl, String remoteFsPort, String clusterName, String tableName)
      throws PegasusSparkException {
    super(remoteFsUrl, remoteFsPort, clusterName, tableName);
  }

  /**
   * table id
   *
   * @param tableId
   * @return this
   */
  public BulkLoaderConfig setTableId(int tableId) {
    this.tableId = tableId;
    return this;
  }

  /**
   * table partition count
   *
   * @param tablePartitionCount
   * @return this
   */
  public BulkLoaderConfig setTablePartitionCount(int tablePartitionCount) {
    this.tablePartitionCount = tablePartitionCount;
    return this;
  }

  /**
   * set the bulkloader data root path, default is "/pegasus-bulkloader"
   *
   * @param dataPathRoot data path root
   * @return this
   */
  public BulkLoaderConfig setDataPathRoot(String dataPathRoot) {
    this.dataPathRoot = dataPathRoot;
    return this;
  }

  /**
   * set whether to distinct the keys of rocksdb records generated by resource data
   *
   * @param distinct true or false, default is "false"
   * @return this
   */
  public BulkLoaderConfig enableDistinct(boolean distinct) {
    isDistinct = distinct;
    return this;
  }

  /**
   * set whether to sort the keys of rocksdb records generated by resource data
   *
   * @param sort true or false, default is "true"
   * @return this
   */
  public BulkLoaderConfig enableSort(boolean sort) {
    isSort = sort;
    return this;
  }
}
